print("[BobBlocks] loading Blocks")
dofile(core.get_modpath("bobblocks") .. "/blocks.lua")
print("[BobBlocks] loaded Blocks")
print("[BobBlocks] loading Health")
dofile(core.get_modpath("bobblocks") .. "/health.lua")
print("[BobBlocks] loaded Health")
print("[BobBlocks] loading Traps")
dofile(core.get_modpath("bobblocks") .. "/trap.lua")
print("[BobBlocks] loaded Traps")
print("[BobBlocks] Mod loaded successfully!")

